/**
 * Study Book — markdown loading, rendering, TOC extraction, and search.
 * All UI state lives in runtime.studyBook (see main.js).
 * This module has no side effects; it exports pure functions and a cache.
 */

import { marked } from "marked";
import DOMPurify from "dompurify";

// ── marked configuration ───────────────────────────────────────────────────

marked.use({
  gfm: true,
  breaks: false,
  // Generate stable id attributes on headings so TOC anchors work.
  hooks: {
    postprocess(html) {
      return html;
    },
  },
  renderer: (() => {
    const renderer = new marked.Renderer();
    renderer.heading = function ({ text, depth }) {
      const anchor = text
        .toLowerCase()
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
      return `<h${depth} id="${anchor}">${text}</h${depth}>\n`;
    };
    return renderer;
  })(),
});

// ── Markdown cache ─────────────────────────────────────────────────────────

const mdCache = new Map(); // path → raw markdown string

/**
 * Fetches a markdown file by path. Returns the cached version on repeat calls.
 * Throws if the fetch fails.
 */
export async function loadMarkdownFile(path) {
  if (mdCache.has(path)) return mdCache.get(path);
  const res = await fetch(path);
  if (!res.ok) throw new Error(`Study Book: could not load "${path}" (${res.status})`);
  const text = await res.text();
  mdCache.set(path, text);
  return text;
}

/**
 * Convenience loader that reads contentMdPath from a manifest dataset entry.
 * Returns null if the dataset has no contentMdPath.
 */
export async function loadContentMarkdown(dataset) {
  if (!dataset?.contentMdPath) return null;
  return loadMarkdownFile(dataset.contentMdPath);
}

// ── Rendering ──────────────────────────────────────────────────────────────

const ALLOWED_TAGS = [
  "h1", "h2", "h3", "h4", "h5", "h6",
  "p", "ul", "ol", "li",
  "table", "thead", "tbody", "tr", "th", "td",
  "blockquote", "pre", "code",
  "strong", "em", "a", "hr", "br",
  "span", "div", "mark",
];
const ALLOWED_ATTR = ["href", "id", "class", "target", "rel"];

/**
 * Parses raw markdown to sanitized HTML ready for innerHTML assignment.
 */
export function renderMarkdown(rawMarkdown) {
  const dirty = marked.parse(rawMarkdown);
  return DOMPurify.sanitize(dirty, { ALLOWED_TAGS, ALLOWED_ATTR });
}

// ── Table of contents ──────────────────────────────────────────────────────

/**
 * Extracts h1/h2/h3 headings from raw markdown and returns a TOC array.
 * Each entry: { level: 1|2|3, text: string, anchor: string }
 * The anchor matches the id generated by the custom renderer above.
 */
export function extractTOC(rawMarkdown) {
  const toc = [];
  const re = /^(#{1,3})\s+(.+)$/gm;
  let match;
  while ((match = re.exec(rawMarkdown)) !== null) {
    const level = match[1].length;
    const text = match[2].trim();
    const anchor = text
      .toLowerCase()
      .replace(/[^\w\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
    toc.push({ level, text, anchor });
  }
  return toc;
}

// ── Search / highlight ─────────────────────────────────────────────────────

/**
 * Wraps every occurrence of `query` in the rendered HTML with
 * <mark class="sb-highlight">…</mark>.
 * Returns { html: string, count: number }.
 * Returns the original html unchanged if query is too short.
 */
export function highlightMatches(html, query) {
  if (!query || query.trim().length < 2) return { html, count: 0 };
  const escaped = query.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`(${escaped})`, "gi");
  let count = 0;
  const highlighted = html.replace(re, (m) => {
    count++;
    return `<mark class="sb-highlight">${m}</mark>`;
  });
  return { html: highlighted, count };
}

// ── Dataset helpers ────────────────────────────────────────────────────────

/**
 * Returns true if the dataset has at least one markdown file registered.
 */
export function datasetHasStudyBook(dataset) {
  return !!(dataset?.contentMdPath || dataset?.extraMdFiles?.length);
}

/**
 * Returns an ordered list of { title, path } for all MD files in a dataset.
 * The primary contentMdPath is listed first with the title "Notes".
 */
export function getStudyBookFiles(dataset) {
  const files = [];
  if (dataset?.contentMdPath) {
    files.push({ title: "Notes", path: dataset.contentMdPath });
  }
  for (const extra of dataset?.extraMdFiles ?? []) {
    if (extra?.path) files.push({ title: extra.title || "More notes", path: extra.path });
  }
  return files;
}
