import PronunciationButton from "./PronunciationButton.jsx";

function rootIsKnown(moduleProgress, root) { return (moduleProgress.roots?.[root.key]?.exposures || 0) > 0 || Boolean(moduleProgress.discoveredNodes?.[`root-${root.key.toLowerCase()}`]); }

function RootFocus({ model, method, pronounce, onOpenPanel, onSelectRoot }) {
  const root = model.currentRoot;
  return <aside className="cik-root-focus lw-card" data-testid="chinese-input-root-focus">
    <div className="cik-panel-heading"><div><p className="lw-eyebrow">Current focus</p><h2>Root Focus</h2></div><button className="lw-btn lw-btn-secondary" type="button" onClick={() => onOpenPanel("keyboard")}>Keyboard</button></div>
    <div className="cik-root-focus-main"><span className="cik-root-focus-glyph" lang="zh-Hant">{root.primaryRoot}</span><div><strong>{root.key} · {root.labelEn}</strong><p lang="zh-Hant">{root.mnemonic.zhHant}</p><p>{root.mnemonic.en}</p><PronunciationButton text={root.primaryRoot} pronounce={pronounce} label="Hear root" /></div></div>
    <div className="cik-related-list" aria-label="Related characters"><p className="lw-eyebrow">Related characters</p>{model.relatedCharacters.length ? model.relatedCharacters.map((character) => <button type="button" key={character.id} onClick={() => onOpenPanel("collection")}><span lang="zh-Hant">{character.char}</span><small>{character[method]?.preferredCode}</small></button>) : <span className="lw-subtitle">Explore a root to find related characters.</span>}</div>
    <button className="lw-btn lw-btn-ghost" type="button" onClick={() => onSelectRoot(root.key)}>Keep this root in focus</button>
  </aside>;
}

function JourneyCard({ model, onStart, onOpenPanel }) {
  const selected = model.selected;
  const title = selected?.title?.en || "Choose your next step";
  const isResume = model.reasonCodes.includes("RESUME_SESSION");
  return <section className="cik-journey-card lw-card" data-testid="chinese-input-recommendation"><div className="cik-journey-card-copy"><p className="lw-eyebrow">{isResume ? "Resume Journey" : selected?.kind === "review" ? "Review suggestion" : "Today’s Journey"}</p><h2>{title}</h2>{selected?.title?.zhHant && <p lang="zh-Hant">{selected.title.zhHant}</p>}<p className="lw-subtitle">{model.summary}</p><div className="cik-journey-meta"><span>{model.estimatedMinutes || 5} min</span><span>{model.learner.dueCount ? `${model.learner.dueCount} ready to revisit` : "Open to choose"}</span></div></div><div className="cik-journey-card-actions"><button className="lw-btn lw-btn-primary" type="button" data-testid="chinese-input-start-lesson" onClick={() => onStart(selected)} disabled={!selected}>{isResume ? "Resume Journey" : selected?.kind === "review" ? "Start review" : "Start Journey"}</button><button className="lw-btn lw-btn-ghost" type="button" onClick={() => onOpenPanel("why")}>Why this?</button><button className="lw-btn lw-btn-secondary" type="button" onClick={() => onOpenPanel("journeys")}>Choose something else</button></div></section>;
}

function KnowledgeMap({ dataset, moduleProgress, currentKey, accessibleListView, onToggleList, onSelectRoot }) {
  return <section className={`cik-knowledge-map lw-card${accessibleListView ? " is-list-view" : ""}`} data-testid="chinese-input-knowledge-world"><div className="cik-panel-heading"><div><p className="lw-eyebrow">Knowledge world</p><h2>Explore the roots</h2><p className="lw-subtitle">Choose any root. Readiness guides you; it never locks the way.</p></div><button className="lw-btn lw-btn-secondary" type="button" onClick={onToggleList}>{accessibleListView ? "Illustrated view" : "List view"}</button></div><div className="cik-root-map" aria-label="Cangjie root knowledge map">{dataset.roots.filter((root) => root.enabled !== false).map((root) => <button type="button" className={`cik-root-node${root.key === currentKey ? " is-current" : ""}${rootIsKnown(moduleProgress, root) ? " is-discovered" : ""}`} key={root.id} onClick={() => onSelectRoot(root.key)} aria-label={`${root.key}, ${root.labelEn}, ${rootIsKnown(moduleProgress, root) ? "discovered" : "not explored"}`} aria-pressed={root.key === currentKey} data-testid={`chinese-input-world-root-${root.key}`}><span className="cik-root-node-key">{root.key}</span><span className="cik-root-node-glyph" lang="zh-Hant">{root.primaryRoot}</span><small>{root.labelEn}</small></button>)}</div></section>;
}

function Companion({ message, minimized, onToggle }) { return <aside className={`cik-companion lw-card${minimized ? " is-minimized" : ""}`}><div className="cik-companion-avatar" aria-hidden="true">🦊</div>{!minimized && <p>{message}</p>}<button type="button" onClick={onToggle} aria-label={minimized ? "Show learning guide" : "Minimise learning guide"}>{minimized ? "Guide" : "×"}</button></aside>; }

export default function ChineseInputWorldHome({ dataset, method, moduleProgress, model, prefs, warning, pronounce, onMethodChange, onOpenPanel, onStart, onSelectRoot, onToggleList, onToggleCompanion }) {
  return <div className="cik-world-home" data-testid="chinese-input-dashboard"><header className="cik-world-header"><div><p className="lw-eyebrow">FoxChild@Learn · Chinese Input Kingdom</p><h1>Chinese Input Kingdom</h1><p className="lw-subtitle">Explore Traditional Chinese roots, build verified codes, and return to the knowledge that needs you next.</p></div><div className="cik-method-switch" role="group" aria-label="Input method">{[["cangjie", "Cangjie 倉頡"], ["quick", "Quick 速成"]].map(([value, label]) => <button key={value} className={`lw-btn ${method === value ? "lw-btn-primary" : "lw-btn-secondary"}`} type="button" aria-pressed={method === value} onClick={() => onMethodChange(value)}>{label}</button>)}</div></header>{warning && <details className="cik-preview-warning" data-testid="chinese-input-preview-warning"><summary>Preview curriculum notice</summary><p>{warning}</p></details>}<div className="cik-world-hud" aria-label="Learning status"><span><strong>{model.learner.dueCount}</strong><small>ready to revisit</small></span><span><strong>{model.learner.weakCount}</strong><small>developing skills</small></span><span><strong>{Object.keys(moduleProgress.discoveredNodes || {}).length}</strong><small>discoveries</small></span><span><strong>{method === "quick" ? "Quick" : "Cangjie 5"}</strong><small>current method</small></span></div><JourneyCard model={model} onStart={onStart} onOpenPanel={onOpenPanel} /><div className="cik-world-grid"><KnowledgeMap dataset={dataset} moduleProgress={moduleProgress} currentKey={prefs.currentRootKey || model.currentRoot.key} accessibleListView={prefs.accessibleListView === true} onToggleList={onToggleList} onSelectRoot={onSelectRoot} /><RootFocus model={model} method={method} pronounce={pronounce} onOpenPanel={onOpenPanel} onSelectRoot={onSelectRoot} /></div><Companion message={model.learner.dueCount ? "A few characters are ready to revisit. Review is a suggestion, never a gate." : `You are exploring ${model.currentRoot.key} · ${model.currentRoot.labelEn}. Choose any root or follow your Journey.`} minimized={prefs.companionMinimized === true} onToggle={onToggleCompanion} /><p className="cik-standard-note">Verified {dataset.characters.length.toLocaleString()} characters · {dataset.lessons.length.toLocaleString()} lessons · {dataset.manifest.datasetVersion} data · {method === "quick" ? "Quick 速成" : "Cangjie 5 倉頡五代"} · progress saves locally on this device.</p></div>;
}
